version: '3.8'

services:
  sonarqube:
    image: sonarqube:community
    restart: always
    container_name: sonarqube
    hostname: sonarqube.docker
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default
      - gitlab
    ports:
      - "127.0.0.1:9000:9000"
    env_file: ./conf.d/sonarqube.env

  postgres:
    image: postgres
    restart: always
    container_name: sonarqube-db
    env_file: ./conf.d/postgres.env
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./data/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sonar" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    name: sonarqube
    driver: bridge
  gitlab: # Идентификатор сети GitLab'a, необходимо чтобы она была прописана в его docker-compose.yml
    external: true